In [ ]:
import pandas as pd
import numpy as np

In [ ]:
 data = pd.read_csv(
    "IMDB Dataset.csv",
    engine="python",
    on_bad_lines="skip"
)

In [ ]:
data.shape

(11825, 2)

In [ ]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

LowerCasing#

In [ ]:
data.review[3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [ ]:
data["review"]=data["review"].str.lower()

In [ ]:
data["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
11820    chan-wook park, you have to hand it to the guy...
11821    i could not agree more with the quote "this is...
11822    i thought the movie (especially the plot) need...
11823    some fraud girl tries to compete in the big le...
11824    this 1970 hit film has not aged well, but fran...
Name: review, Length: 11825, dtype: object

Removing HTML TAG#

In [ ]:
import re
def remove_tag(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)

# import re
# data["review"]=data["review"].str.replace(r"<.*?>","",regex=True)
# data["review"].head()

In [ ]:
data["review"].apply(remove_tag)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
11820    chan-wook park, you have to hand it to the guy...
11821    i could not agree more with the quote "this is...
11822    i thought the movie (especially the plot) need...
11823    some fraud girl tries to compete in the big le...
11824    this 1970 hit film has not aged well, but fran...
Name: review, Length: 11825, dtype: object

Remove URLs

In [ ]:
tesx1="check out my netbook https://www.kaggle.com"

In [ ]:
def remove_urls(text):
  pattern=re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [ ]:
remove_urls(tesx1)

'check out my netbook '

Remove Punctuation like !@#$%^^&*(()}{"::;'><?

In [ ]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude=string.punctuation

In [ ]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
  return text

In [ ]:
data["review"].apply(remove_punc)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production br br the filmin...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
11820    chanwook park you have to hand it to the guy i...
11821    i could not agree more with the quote this is ...
11822    i thought the movie especially the plot needs ...
11823    some fraud girl tries to compete in the big le...
11824    this 1970 hit film has not aged well but frank...
Name: review, Length: 11825, dtype: object

In [ ]:
tesx="""String hi. you are best! i am happy! "name is kriti"""

In [ ]:
remove_punc(tesx)

'String hi you are best i am happy name is kriti'

In [ ]:
# def remove_punc(text):
#     return text.translate(str.maketrans('', '', string.punctuation)) this tekes less time

Chat Word TreatMent
like we do Big words to small words so here we use chat word Treatment

In [ ]:
raw_text="""A3=Anytime, Anywhere, Anyplace
ADIH=Another Day In Hell
AFK=Away From Keyboard
AFAIK=As Far As I Know
ASAP=As Soon As Possible
ASL=Age, Sex, Location
ATK=At The Keyboard
ATM=At The Moment
BAE=Before Anyone Else
BAK=Back At Keyboard
BBL=Be Back Later
BBS=Be Back Soon
BFN=Bye For Now
B4N=Bye For Now
BRB=Be Right Back
BRUH=Bro
BRT=Be Right There
BSAAW=Big Smile And A Wink
BTW=By The Way
BWL=Bursting With Laughter
CSL=Can’t Stop Laughing
CU=See You
CUL8R=See You Later
CYA=See You
DM=Direct Message
FAQ=Frequently Asked Questions
FC=Fingers Crossed
FIMH=Forever In My Heart
FOMO=Fear Of Missing Out
FR=For Real
FWIW=For What It's Worth
FYP=For You Page
FYI=For Your Information
G9=Genius
GAL=Get A Life
GG=Good Game
GMTA=Great Minds Think Alike
GN=Good Night
GOAT=Greatest Of All Time
GR8=Great!
HBD=Happy Birthday
IC=I See
ICQ=I Seek You
IDC=I Don’t Care
IDK=I Don't Know
IFYP=I Feel Your Pain
ILU=I Love You
ILY=I Love You
IMHO=In My Honest/Humble Opinion
IMU=I Miss You
IMO=In My Opinion
IOW=In Other Words
IRL=In Real Life
IYKYK=If You Know, You Know
JK=Just Kidding
KISS=Keep It Simple, Stupid
L=Loss
L8R=Later
LDR=Long Distance Relationship
LMK=Let Me Know
LMAO=Laughing My A** Off
LOL=Laughing Out Loud
LTNS=Long Time No See
M8=Mate
MFW=My Face When
MID=Mediocre
MRW=My Reaction When
MTE=My Thoughts Exactly
NVM=Never Mind
NRN=No Reply Necessary
NPC=Non-Player Character
OIC=Oh I See
OP=Overpowered
PITA=Pain In The A**
POV=Point Of View
PRT=Party
PRW=Parents Are Watching
ROFL=Rolling On The Floor Laughing
ROFLOL=Rolling On The Floor Laughing Out Loud
ROTFLMAO=Rolling On The Floor Laughing My A** Off
RN=Right Now
SK8=Skate
STATS=Your Sex And Age
SUS=Suspicious
TBH=To Be Honest
TFW=That Feeling When
THX=Thank You
TIME=Tears In My Eyes
TLDR=Too Long, Didn’t Read
TNTL=Trying Not To Laugh
TTFN=Ta-Ta For Now!
TTYL=Talk To You Later
U=You
U2=You Too
U4E=Yours For Ever
W=Win
W8=Wait...
WB=Welcome Back
WTF=What The F**k
WTG=Way To Go!
WUF=Where Are You From?
WYD=What You Doing?
WYWH=Wish You Were Here
ZZZ=Sleeping, Bored, Tired"""

In [ ]:
rows = []

for line in raw_text.strip().split("\n"):
    if "=" in line:
        key, value = line.split("=", 1)
        rows.append([key.strip(), value.strip()])

In [ ]:
df_slang = pd.DataFrame(rows,columns=["short_form", "full_form"])
df_slang.head()

  short_form                    full_form
0         A3  Anytime, Anywhere, Anyplace
1       ADIH          Another Day In Hell
2        AFK           Away From Keyboard
3      AFAIK             As Far As I Know
4       ASAP          As Soon As Possible

In [ ]:
df_slang[df_slang["short_form"] == "AFK"]

  short_form           full_form
2        AFK  Away From Keyboard

In [ ]:
slang_dict = dict(zip(df_slang["short_form"], df_slang["full_form"]))

In [ ]:
print(slang_dict["AFK"])

Away From Keyboard

In [ ]:
def expand_slang(text):
    words = text.split()
    return " ".join(slang_dict.get(word, word) for word in words)
print(expand_slang("BRB I am AFK"))

Be Right Back I am Away From Keyboard

Spelling Misteak

In [ ]:
from textblob import TextBlob

In [ ]:
incorrect="ceertain conditon sevral qqustin"
textblb=TextBlob(incorrect)
textblb.correct().string

'certain condition several austin'

Removing Stop Words like a the off are

In [ ]:
from nltk.corpus import stopwords

In [ ]:
stopwords.words('english')

LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

In [ ]:
import re

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # Emoticons
        "\U0001F300-\U0001F5FF"  # Symbols & pictographs
        "\U0001F680-\U0001F6FF"  # Transport & map
        "\U0001F1E0-\U0001F1FF"  # Flags
        "\U00002700-\U000027BF"
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

# Example
text = "Hello 😊🚀 World 🌍"
print(remove_emojis(text))

Hello  World